source "https://rubygems.org"

gem "fluent-plugin-prometheus", "~> 1.6.1"
gem "rdkafka", "~> 0.7.0"
gem "fluent-plugin-kafka", "~> 0.12.2"
gem "snappy", "~> 0.0.15"
gem "fluent-plugin-systemd", "~> 1.0.1"
